//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication.CurrencyService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/WCFService")]
    [System.SerializableAttribute()]
    public partial class ServiceFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CurrencyService.INumberToCurrencyWordsService")]
    public interface INumberToCurrencyWordsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INumberToCurrencyWordsService/GetCurrencyWords", ReplyAction="http://tempuri.org/INumberToCurrencyWordsService/GetCurrencyWordsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WpfApplication.CurrencyService.ServiceFault), Action="http://tempuri.org/INumberToCurrencyWordsService/GetCurrencyWordsServiceFaultFaul" +
            "t", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/WCFService")]
        string GetCurrencyWords(string amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INumberToCurrencyWordsService/GetCurrencyWords", ReplyAction="http://tempuri.org/INumberToCurrencyWordsService/GetCurrencyWordsResponse")]
        System.Threading.Tasks.Task<string> GetCurrencyWordsAsync(string amount);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INumberToCurrencyWordsServiceChannel : WpfApplication.CurrencyService.INumberToCurrencyWordsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NumberToCurrencyWordsServiceClient : System.ServiceModel.ClientBase<WpfApplication.CurrencyService.INumberToCurrencyWordsService>, WpfApplication.CurrencyService.INumberToCurrencyWordsService {
        
        public NumberToCurrencyWordsServiceClient() {
        }
        
        public NumberToCurrencyWordsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NumberToCurrencyWordsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NumberToCurrencyWordsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NumberToCurrencyWordsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetCurrencyWords(string amount) {
            return base.Channel.GetCurrencyWords(amount);
        }
        
        public System.Threading.Tasks.Task<string> GetCurrencyWordsAsync(string amount) {
            return base.Channel.GetCurrencyWordsAsync(amount);
        }
    }
}
