//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTests.CurrencyService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CurrencyService.INumberToCurrencyWordsService")]
    public interface INumberToCurrencyWordsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INumberToCurrencyWordsService/GetCurrencyWords", ReplyAction="http://tempuri.org/INumberToCurrencyWordsService/GetCurrencyWordsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFService.ServiceFault), Action="http://tempuri.org/INumberToCurrencyWordsService/GetCurrencyWordsServiceFaultFaul" +
            "t", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/WCFService")]
        string GetCurrencyWords(string amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INumberToCurrencyWordsService/GetCurrencyWords", ReplyAction="http://tempuri.org/INumberToCurrencyWordsService/GetCurrencyWordsResponse")]
        System.Threading.Tasks.Task<string> GetCurrencyWordsAsync(string amount);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INumberToCurrencyWordsServiceChannel : UnitTests.CurrencyService.INumberToCurrencyWordsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NumberToCurrencyWordsServiceClient : System.ServiceModel.ClientBase<UnitTests.CurrencyService.INumberToCurrencyWordsService>, UnitTests.CurrencyService.INumberToCurrencyWordsService {
        
        public NumberToCurrencyWordsServiceClient() {
        }
        
        public NumberToCurrencyWordsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NumberToCurrencyWordsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NumberToCurrencyWordsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NumberToCurrencyWordsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetCurrencyWords(string amount) {
            return base.Channel.GetCurrencyWords(amount);
        }
        
        public System.Threading.Tasks.Task<string> GetCurrencyWordsAsync(string amount) {
            return base.Channel.GetCurrencyWordsAsync(amount);
        }
    }
}
